# Generated by Django 3.1.6 on 2022-04-21 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GotchaSys', '0002_item_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='text',
            new_name='text1',
        ),
    ]
