# Generated by Django 3.1.6 on 2022-06-29 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GotchaSys', '0004_auto_20220509_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('Character_Rarity', models.IntegerField()),
                ('Char_Description', models.TextField(default='')),
                ('Character_ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CharType',
            fields=[
                ('Char_Range', models.CharField(max_length=25)),
                ('Class_Desc', models.TextField(default='')),
                ('Pref_Gear', models.TextField(default='')),
                ('CharClass', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('CharType_CharID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='GotchaSys.characters')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('Equip_Weapons', models.TextField(default='')),
                ('Equip_Essentials', models.TextField(default='')),
                ('Other_Equip', models.TextField(default='')),
                ('EquipID', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('Equip_CharID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GotchaSys.characters')),
                ('Equip_CharType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GotchaSys.chartype')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.IntegerField()),
                ('query', models.TextField(default='')),
                ('User_ID', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Gacha',
            fields=[
                ('Banner_Type', models.CharField(max_length=20)),
                ('Banner_Description', models.TextField(default='')),
                ('Banner_ReleaseDate', models.DateField()),
                ('Banner_EndDate', models.DateField()),
                ('Banner_ID', models.CharField(max_length=80, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('Genre', models.CharField(max_length=30)),
                ('Release_Date', models.DateField()),
                ('Game_Description', models.TextField(default='')),
                ('Game_ID', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Storylines',
            fields=[
                ('Chapter_Description', models.TextField(default='')),
                ('Chapter_Setting', models.TextField(default='')),
                ('Chapter_ID', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('Story_GameID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GotchaSys.games')),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='gacha',
            name='Gacha_GameID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GotchaSys.games'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='User_Game',
            field=models.ManyToManyField(to='GotchaSys.Games'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='Equip_GameID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GotchaSys.games'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='Equip_Story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GotchaSys.storylines'),
        ),
        migrations.AddField(
            model_name='chartype',
            name='CharType_GameID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GotchaSys.games'),
        ),
        migrations.AddField(
            model_name='characters',
            name='Char_GachaID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GotchaSys.gacha'),
        ),
        migrations.AddField(
            model_name='characters',
            name='Char_GameID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GotchaSys.games'),
        ),
        migrations.AddField(
            model_name='characters',
            name='Char_StoryID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GotchaSys.storylines'),
        ),
    ]
