# Generated by Django 3.1.6 on 2022-07-01 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GotchaSys', '0005_auto_20220629_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='User_Game',
        ),
    ]
