# Generated by Django 3.1.6 on 2022-07-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GotchaSys', '0006_remove_feedback_user_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='Game_Name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='games',
            name='Game_ID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
