# Generated by Django 3.1.6 on 2022-07-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GotchaSys', '0007_auto_20220706_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storylines',
            name='Chapter_ID',
            field=models.BigAutoField(max_length=70, primary_key=True, serialize=False),
        ),
    ]
