# Generated by Django 3.1.6 on 2022-07-07 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GotchaSys', '0011_characters_character_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characters',
            name='Char_GachaID',
        ),
        migrations.RemoveField(
            model_name='characters',
            name='Char_StoryID',
        ),
    ]
