# Generated by Django 3.1.6 on 2022-07-08 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GotchaSys', '0013_auto_20220708_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='Character_ID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
